### ISSUE TITLE
[Bug]: Hole Curseforge App Launcher crashed while installing your mod

### ISSUE THREAD

**Issue by xR4YM0ND** [TheButterbrotMan/Just-Enough-Hammers#7]
### What happened?

Tried to install -> Launcher crashed every time
[OverwolfLogs_2022-04-26_16-38-31.zip](https://github.com/TheButterbrotMan/Just-Enough-Hammers/files/8564185/OverwolfLogs_2022-04-26_16-38-31.zip)

### Version

1.0.2+1.18.2

**Comment by TheButterbrotMan** [comment]
Have you already forwarded this to cf discord?

**Comment by xR4YM0ND** [comment]
yes they said make an issue and i made one, but the thing is it only happens with your mod so i think it is on your side. 

Maybe with the related mods ? Idk

**Comment by xR4YM0ND** [comment]
I will update you when they responed to the issue

**Comment by TheButterbrotMan** [comment]
> yes they said make an issue and i made one, but the thing is it only happens with your mod so i think it is on your side. 
> 
> Maybe with the related mods ? Idk

Why do you think it's due to related mods?

**Comment by TheButterbrotMan** [comment]
I downloaded it yesterday, worked. I try to fix this if it is on our side. But I'm not sure yet how we could caused this.

**Comment by xR4YM0ND** [comment]
it is just a wild guess

**Comment by TheButterbrotMan** [comment]
So for now, you should be able to download the .jar and put it in until this is solved. I keep it open, although it does seem to be not on our side.

**Comment by xR4YM0ND** [comment]
yes i will do that for now, for later i need it in the modpack but yeah , hope this will get found and fixed <3

**Comment by TheButterbrotMan** [comment]
Maybe it works when, you export it. And then install it try it CF weird sometimes

**Comment by TheButterbrotMan** [comment]
Problem is fixed.

**Comment by xR4YM0ND** [comment]
what was the issue?
