### ISSUE TITLE
[Bug]: AdventureZ Error

### ISSUE THREAD

**Issue by xR4YM0ND** [TheButterbrotMan/Just-Enough-Hammers#9]
### What happened?

[latest.log](https://gist.github.com/SpigotDE/ce7609f557c1bd9a8afbc01d108223b9)

### Version

1.0.3-1.18.2

**Comment by xR4YM0ND** [comment]
https://github.com/Globox1997/AdventureZ/issues/98

**Comment by TheButterbrotMan** [comment]
@MikhailTapio Please identify problem

**Comment by xR4YM0ND** [comment]
In the console / log i have some errors: Unknown Item adventurez:gilded_blackstone

**Comment by TheButterbrotMan** [comment]
Fixed in 1.0.4.
